id: P5FB4054D
initial_creation_type: input
source_metadata:
  title: Rongtön Sheja Künrig Series
  language: es
  description: Rongtön Sheja Kunrig (rong ston shes bya kun rig), also known as Shakya
    Gyaltsen, (shakya rgyal mtshan, 1367-1449) was one of the greatest scholars of
    the Sakya school, renowned especially for his mastery of the prajñāpāramitā teachings.
    He founded Nalendra Monastery in 1436.
  volume:
    305794ca5a4543d9817882b95274f563:
      title: 'The Joyous Entrance to the Path to Liberation: How to Practise the Six
        Transcendent Perfections'
      parent: Advice
    7a18728cd4eb4ed5863fc3fd7097ed01:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    ae18c87db8cb49169a6c8eca75ba0040:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: Middle Way
    0e1710c9a15e4cb79fb3c6433710d527:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Praise
    c2925748d4dd4c61a97c96ea91be9c41:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Praise
    610987744ee54d2e84f45f8fd477f054:
      title: Elucidating the Essence of the Instructions for Entering the Three Gateways
        to Liberation
      parent: Three Gateways to Liberation
    da118e0397d945329deb1696c9181748:
      title: 'The Excellent Path of the Great Vehicle: How to Meditate on the Three
        Gateways to Liberation According to the Mahāyāna'
      parent: Three Gateways to Liberation
created_at: '2022-03-01T01:24:12.898637'
last_modified_at: '2022-03-01T01:24:12.898640'
